# Site settings
title: PeterJiao's Blog
email: impeterjiao@163.com
description: 对过去的救赎是现在走的每一步，而不是对未来的规划。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://peterjiao.com/" # the base hostname & protocol for your site
twitter_username: 
github_username:  peterjiao

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: peterjiao
  email: impeterjiao@163.com
  link: http://peterjiao.com/
  weibo: http://weibo.com/675631991
  github: http://github.com/peterjiao
title: PeterJiao's Blog                            #自定义常量

# avatar头像及Favicon
avatar: http://7xind4.com1.z0.glb.clouddn.com/jekyllfavicon.ico
favicon: http://7xind4.com1.z0.glb.clouddn.com/jekyllfavicon.ico
#https://avatars1.githubusercontent.com/u/5010799?v=3&amp;s=460
locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

# google analytics 设置
ga:
  id: 
  url: auto
#
gems: [jekyll-paginate]
